name: Run

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: go build -o ./main -v ./main

      - name: Test
        run: ./main

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: go build -o ./main -v ./main

      - name: Test
        run: ./main
